//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDK
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MDKEntities : DbContext
    {
        public MDKEntities()
            : base("name=MDKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<material> material { get; set; }
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<partner_products_request_> partner_products_request_ { get; set; }
        public virtual DbSet<partner_rating_history> partner_rating_history { get; set; }
        public virtual DbSet<partners_> partners_ { get; set; }
        public virtual DbSet<products_> products_ { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<status_order> status_order { get; set; }
        public virtual DbSet<status_structure_order> status_structure_order { get; set; }
        public virtual DbSet<structure_order> structure_order { get; set; }
        public virtual DbSet<suppliers> suppliers { get; set; }
        public virtual DbSet<suppliers_material> suppliers_material { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<type_material_> type_material_ { get; set; }
        public virtual DbSet<type_partner_> type_partner_ { get; set; }
        public virtual DbSet<type_product_> type_product_ { get; set; }
        public virtual DbSet<type_suppliers> type_suppliers { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
