//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDK
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order()
        {
            this.structure_order = new HashSet<structure_order>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_status_order { get; set; }
        public Nullable<int> id_partner { get; set; }
        public Nullable<int> id_manager { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> prepayment_date { get; set; }
        public string cancel_reason { get; set; }
        public Nullable<double> prepayment_amount { get; set; }
        public Nullable<System.DateTime> full_payment_date { get; set; }
        public Nullable<System.DateTime> completion_date { get; set; }
    
        public virtual partners_ partners_ { get; set; }
        public virtual status_order status_order { get; set; }
        public virtual users users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<structure_order> structure_order { get; set; }
    }
}
