//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDK
{
    using System;
    using System.Collections.Generic;
    
    public partial class partners_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public partners_()
        {
            this.order = new HashSet<order>();
            this.partner_products_request_ = new HashSet<partner_products_request_>();
            this.partner_rating_history = new HashSet<partner_rating_history>();
        }
    
        public int id { get; set; }
        public Nullable<int> type_partner { get; set; }
        public string name { get; set; }
        public string director { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string adress { get; set; }
        public Nullable<double> inn { get; set; }
        public Nullable<double> reiting { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<partner_products_request_> partner_products_request_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<partner_rating_history> partner_rating_history { get; set; }
        public virtual type_partner_ type_partner_ { get; set; }
    }
}
