//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDK
{
    using System;
    using System.Collections.Generic;
    
    public partial class partner_rating_history
    {
        public int id { get; set; }
        public Nullable<int> id_partner { get; set; }
        public Nullable<double> old_rating { get; set; }
        public Nullable<double> new_rating { get; set; }
        public Nullable<System.DateTime> change_date { get; set; }
        public Nullable<int> changed_by_manager { get; set; }
        public string reason { get; set; }
    
        public virtual partners_ partners_ { get; set; }
        public virtual users users { get; set; }
    }
}
