//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDK
{
    using System;
    using System.Collections.Generic;
    
    public partial class partner_products_request_
    {
        public int id { get; set; }
        public Nullable<int> id_product { get; set; }
        public Nullable<int> name_partner { get; set; }
        public Nullable<double> count { get; set; }
    
        public virtual partners_ partners_ { get; set; }
        public virtual products_ products_ { get; set; }
    }
}
