//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDK
{
    using System;
    using System.Collections.Generic;
    
    public partial class products_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public products_()
        {
            this.partner_products_request_ = new HashSet<partner_products_request_>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_type_product { get; set; }
        public string name { get; set; }
        public Nullable<double> Артикул { get; set; }
        public Nullable<double> Минимальная_стоимость_для_партнера { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<partner_products_request_> partner_products_request_ { get; set; }
        public virtual type_product_ type_product_ { get; set; }
    }
}
