//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDK
{
    using System;
    using System.Collections.Generic;
    
    public partial class structure_order
    {
        public int id { get; set; }
        public Nullable<int> id_order { get; set; }
        public Nullable<int> id_product { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> agreed_price { get; set; }
        public Nullable<System.DateTime> production_date { get; set; }
        public Nullable<int> id_status_structure_order { get; set; }
    
        public virtual order order { get; set; }
        public virtual status_structure_order status_structure_order { get; set; }
    }
}
