//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDK
{
    using System;
    using System.Collections.Generic;
    
    public partial class suppliers_material
    {
        public int id { get; set; }
        public Nullable<int> id_suppliers { get; set; }
        public Nullable<int> id_material { get; set; }
    
        public virtual material material { get; set; }
        public virtual suppliers suppliers { get; set; }
    }
}
